<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prasanga Paudel">
<meta name="dcterms.date" content="2025-02-05">

<title>Data Analysis Excerise – Prasanga Paudel’s Data Analysis Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-86daaaaad7353f9cc0c554efc1dd6d94.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-55c119cbca0847612369e51c8a5413ad.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Prasanga Paudel’s Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-excercise/synthetic-data.html">
 <span class="dropdown-text">Synthetic Data Generation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../fitting-exercise/fitting-exercise.html">
 <span class="dropdown-text">Model Fitting Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../ml-models-exercise/ml-models-exercise.html">
 <span class="dropdown-text">Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/xprasanga/prasangapaudel-MADA-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis Excerise</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prasanga Paudel </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 5, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This exercise is based on CDC dataset.</p>
<div style="page-break-after: always;"></div>
<section id="data-acquisition" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Data Acquisition</h1>
<p>In this section we will acquire data from the directory, and have an initial look at it. This data on tax burden across different state was obtained from the annual compendium on tobacco revenue and industry statistics. These datasets are reported on an annual basis, and they include federal and state-level information regarding taxes applied to the price of a pack of cigarettes. The data was last updated on March 22, 2021.</p>
<p>The dataset can be assessed from this link: <a href="https://data.cdc.gov/Policy/Table-of-Gross-Cigarette-Tax-Revenue-Per-State-Orz/rkpp-igza/about_data" class="uri">https://data.cdc.gov/Policy/Table-of-Gross-Cigarette-Tax-Revenue-Per-State-Orz/rkpp-igza/about_data</a></p>
<div style="page-break-after: always;"></div>
<p>#Data Importing</p>
<p>We will now import the data from our repository using the here command. We can observe that there are 2550 observations with 14 variables. The variables some observations can be viewed using the head() command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constructing the file path using here()</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"cdcdata-exercise"</span>,<span class="st">"cigarette-tax.xlsx"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing the Excel file fromthe file path</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>cdc_dataset <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(file_path)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the uppermost data of the imported dataset</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cdc_dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  LocationAbbr LocationDesc  Year Datasource TopicDesc    MeasureDesc Data_Value
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;
1 AL           Alabama       2019 OW         The Tax Bur… Cigarette …  165763113
2 AK           Alaska        2019 OW         The Tax Bur… Cigarette …   44773153
3 AZ           Arizona       2019 OW         The Tax Bur… Cigarette …  296712275
4 AR           Arkansas      2019 OW         The Tax Bur… Cigarette …  161909335
5 CA           California    2019 OW         The Tax Bur… Cigarette … 1791254942
6 CO           Colorado      2019 OW         The Tax Bur… Cigarette …  145551255
# ℹ 7 more variables: Data_Value_Unit &lt;chr&gt;, Data_Value_Type &lt;chr&gt;,
#   GeoLocation &lt;chr&gt;, Source &lt;chr&gt;, TopicTypeId &lt;chr&gt;, TopicId &lt;chr&gt;,
#   MeasureId &lt;chr&gt;</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="data-cleaning" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data Cleaning</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values within the cdc_dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> LocationAbbr       LocationDesc            Year       Datasource       
 Length:2550        Length:2550        Min.   :1970   Length:2550       
 Class :character   Class :character   1st Qu.:1982   Class :character  
 Mode  :character   Mode  :character   Median :1994   Mode  :character  
                                       Mean   :1994                     
                                       3rd Qu.:2007                     
                                       Max.   :2019                     
  TopicDesc         MeasureDesc          Data_Value        Data_Value_Unit   
 Length:2550        Length:2550        Min.   :2.737e+06   Length:2550       
 Class :character   Class :character   1st Qu.:2.812e+07   Class :character  
 Mode  :character   Mode  :character   Median :7.708e+07   Mode  :character  
                                       Mean   :1.701e+08                     
                                       3rd Qu.:2.004e+08                     
                                       Max.   :1.888e+09                     
 Data_Value_Type    GeoLocation           Source          TopicTypeId       
 Length:2550        Length:2550        Length:2550        Length:2550       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
   TopicId           MeasureId        
 Length:2550        Length:2550       
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cdc_dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,550 × 14] (S3: tbl_df/tbl/data.frame)
 $ LocationAbbr   : chr [1:2550] "AL" "AK" "AZ" "AR" ...
 $ LocationDesc   : chr [1:2550] "Alabama" "Alaska" "Arizona" "Arkansas" ...
 $ Year           : num [1:2550] 2019 2019 2019 2019 2019 ...
 $ Datasource     : chr [1:2550] "OW" "OW" "OW" "OW" ...
 $ TopicDesc      : chr [1:2550] "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" ...
 $ MeasureDesc    : chr [1:2550] "Cigarette Sales" "Cigarette Sales" "Cigarette Sales" "Cigarette Sales" ...
 $ Data_Value     : num [1:2550] 1.66e+08 4.48e+07 2.97e+08 1.62e+08 1.79e+09 ...
 $ Data_Value_Unit: chr [1:2550] "$" "$" "$" "$" ...
 $ Data_Value_Type: chr [1:2550] "Dollars" "Dollars" "Dollars" "Dollars" ...
 $ GeoLocation    : chr [1:2550] "POINT (-86.631860762 32.840571122)" "POINT (-147.722059036 64.845079957001)" "POINT (-111.763811277 34.86597028)" "POINT (-92.274490743 34.748650124)" ...
 $ Source         : chr [1:2550] "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" ...
 $ TopicTypeId    : chr [1:2550] "POL" "POL" "POL" "POL" ...
 $ TopicId        : chr [1:2550] "450POL" "450POL" "450POL" "450POL" ...
 $ MeasureId      : chr [1:2550] "450CGS" "450CGS" "450CGS" "450CGS" ...</code></pre>
</div>
</div>
<p>We have one (continuous) numeric variable in out dataset under that name “Data_Value”. This variable actually represents the dollar amount of the revenue generated from cigarette sales. Another variable “Year” which represents the year of data collection has also been coded as numeric. The rest of the variables are coded as character as they have alphabets as values including the TopicID and MeasureId variables. The variable “LocationDesc” represents the name of the States.</p>
<section id="checking-for-missing-values" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="checking-for-missing-values"><span class="header-section-number">2.1</span> Checking for missing values</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values (NA) within the dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(cdc_dataset))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   LocationAbbr    LocationDesc            Year      Datasource       TopicDesc 
              0               0               0               0               0 
    MeasureDesc      Data_Value Data_Value_Unit Data_Value_Type     GeoLocation 
              0               0               0               0               0 
         Source     TopicTypeId         TopicId       MeasureId 
              0               0               0               0 </code></pre>
</div>
</div>
<p>We can observe that there are 14 variables altogether and there are no missing values in the dataset. We will further check for any missing values coded as 9999 for any numeric variable. We will also use scatterplot to see if there is any such replacement for missing value which can be observed as an outlier. This can be observed later during the analysis.</p>
</section>
<section id="confirming-the-structure-of-the-dataset-through-observation-across-states" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="confirming-the-structure-of-the-dataset-through-observation-across-states"><span class="header-section-number">2.2</span> Confirming the structure of the dataset through observation across States</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting the number of observations per State</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>state_counts <span class="ot">&lt;-</span> cdc_dataset <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(LocationDesc)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the result</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 2
   LocationDesc             n
   &lt;chr&gt;                &lt;int&gt;
 1 Alabama                 50
 2 Alaska                  50
 3 Arizona                 50
 4 Arkansas                50
 5 California              50
 6 Colorado                50
 7 Connecticut             50
 8 Delaware                50
 9 District of Columbia    50
10 Florida                 50
# ℹ 41 more rows</code></pre>
</div>
</div>
<p>We can confirm that every state has 50 oservations for each State from year 1970-2019, which makes perfect sense.</p>
<div style="page-break-after: always;"></div>
<p>#Preparing the dataset for replicable properties As the raw data itself is quite messy, we will try to make it as simple as possible to learn about their distribution. As this is a time-series data, we will focus on the “trend” rather than the distribution as normal. We will try to clean the data as much as possible so that we can observe consisteny in the result, making it easier to learn about the properties of the dataset.</p>
</section>
<section id="filtering-out-five-states-to-make-the-analysis-easy." class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="filtering-out-five-states-to-make-the-analysis-easy."><span class="header-section-number">2.3</span> Filtering out Five states to make the analysis easy.</h2>
<p>We will filter five states from the dataset and make a new dataset based on these states, The next phases of analysis will include these states only: Georgia, Kansas, Idaho, Alabama and Nebraska.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter dataset for selected states</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>filtered_states <span class="ot">&lt;-</span> cdc_dataset <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LocationDesc <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Georgia"</span>, <span class="st">"Kansas"</span>, <span class="st">"Idaho"</span>, <span class="st">"Alabama"</span>, <span class="st">"Nebraska"</span>))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new dataset</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(filtered_states)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  LocationAbbr LocationDesc  Year Datasource TopicDesc    MeasureDesc Data_Value
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;
1 AL           Alabama       2019 OW         The Tax Bur… Cigarette …  165763113
2 GA           Georgia       2019 OW         The Tax Bur… Cigarette …  168549095
3 ID           Idaho         2019 OW         The Tax Bur… Cigarette …   35817868
4 KS           Kansas        2019 OW         The Tax Bur… Cigarette …  116778114
5 NE           Nebraska      2019 OW         The Tax Bur… Cigarette …   50168160
6 AL           Alabama       2018 OW         The Tax Bur… Cigarette …  172649066
# ℹ 7 more variables: Data_Value_Unit &lt;chr&gt;, Data_Value_Type &lt;chr&gt;,
#   GeoLocation &lt;chr&gt;, Source &lt;chr&gt;, TopicTypeId &lt;chr&gt;, TopicId &lt;chr&gt;,
#   MeasureId &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="filtering-out-the-variables-of-interest" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="filtering-out-the-variables-of-interest"><span class="header-section-number">2.4</span> Filtering out the variables of interest</h2>
<p>In this section, we will filter out only five variables so that we can look through the dataset more easily. We will set the name to this dataset as “dataset”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only the required columns</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> filtered_states <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LocationDesc, LocationAbbr, Year, Data_Value, GeoLocation)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new dataset</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  LocationDesc LocationAbbr  Year Data_Value GeoLocation                        
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;                              
1 Alabama      AL            2019  165763113 POINT (-86.631860762 32.840571122) 
2 Georgia      GA            2019  168549095 POINT (-83.627580346 32.839681093) 
3 Idaho        ID            2019   35817868 POINT (-114.363730042 43.682630005)
4 Kansas       KS            2019  116778114 POINT (-98.200781227 38.3477403)   
5 Nebraska     NE            2019   50168160 POINT (-99.365720623 41.6410409880…
6 Alabama      AL            2018  172649066 POINT (-86.631860762 32.840571122) </code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="visualizing-the-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Visualizing the data</h1>
<p>We will use multiple techniques to visualize and summarize the dataset so that it will be easy for other classmates to understand the structure behind the data..</p>
<section id="scatter-plot-of-revenue-across-time-for-our-five-states." class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="scatter-plot-of-revenue-across-time-for-our-five-states."><span class="header-section-number">3.1</span> Scatter plot of Revenue across time for our five states.</h2>
<p>We will first use scatter plot to observe the property of our numeric variable Data_Value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining the custom colors for each state so it is easy for us to observe</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Georgia"</span> <span class="ot">=</span> <span class="st">"red"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Kansas"</span> <span class="ot">=</span> <span class="st">"blue"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Idaho"</span> <span class="ot">=</span> <span class="st">"green"</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Nebraska"</span> <span class="ot">=</span> <span class="st">"purple"</span>, </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Alabama"</span> <span class="ot">=</span> <span class="st">"orange"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot of Year vs Data_Value</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Data_Value, <span class="at">color =</span> LocationDesc)) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> custom_colors) <span class="sc">+</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Data_Value Over Time for Selected States"</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Data Value"</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"State"</span>) <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As there is a sudden break in the pattern after the year 2000, we will remove these years from our dataset and create a new dataset based on years 1970-2000.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="further-cleaning-of-the-dataset" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Further Cleaning of the dataset</h1>
<p>We will create a new datset based on year 1970 to 2000 which because they show somewhat consistent trend among the data_valuei.e revenue value</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering dataset for years less than 2001</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&lt;</span> <span class="dv">2001</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the first few rows of the newly filtered dataset</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  LocationDesc LocationAbbr  Year Data_Value GeoLocation                        
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;                              
1 Alabama      AL            2000   70664938 POINT (-86.631860762 32.840571122) 
2 Georgia      GA            2000   84389385 POINT (-83.627580346 32.839681093) 
3 Idaho        ID            2000   25249502 POINT (-114.363730042 43.682630005)
4 Kansas       KS            2000   50886541 POINT (-98.200781227 38.3477403)   
5 Nebraska     NE            2000   44993900 POINT (-99.365720623 41.6410409880…
6 Alabama      AL            1999   71844367 POINT (-86.631860762 32.840571122) </code></pre>
</div>
</div>
<p>We can observe that we now have 155 observations with 5 variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting the number of observations per state again.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>state_counts2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(LocationDesc)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the count result</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_counts2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  LocationDesc     n
  &lt;chr&gt;        &lt;int&gt;
1 Alabama         31
2 Georgia         31
3 Idaho           31
4 Kansas          31
5 Nebraska        31</code></pre>
</div>
</div>
<p>Here, we can observe we have 31 observations for each State across 1970-2000</p>
<div style="page-break-after: always;"></div>
</section>
<section id="association-of-variables-in-final-dataset" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Association of variables in final Dataset</h1>
<p>This section will talk about the association of revenue within the five state across the year 1970-2000. We will use few figures and a regression analysis to get some idea of the relationship.</p>
<section id="scatter-plot-of-revenue-across-time-for-our-five-states.-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="scatter-plot-of-revenue-across-time-for-our-five-states.-1"><span class="header-section-number">5.1</span> Scatter plot of Revenue across time for our five states.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Data_Value, <span class="co">#setting the axes</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> LocationDesc)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Adding a linear trend line</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trend of Revenue from Cigarette(in US$) Over Years by State"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Revenue Value"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"State"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This figure clearly shows the relation between the variables across time and States. This relation will be more clear if we use gregression analysis to calculate the slope. We will do that in next step. The scatter plot also confirms that there is no such missing value as encoded as 9999 otherwise we would have seen it as an outlier in our scatterplots.</p>
</section>
<section id="calculating-slope-or-association-through-regression" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="calculating-slope-or-association-through-regression"><span class="header-section-number">5.2</span> Calculating Slope or association through Regression</h2>
<p>We will now try to express the relation of revenue over time for Georgia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data for Georgia</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>georgia_data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LocationDesc <span class="sc">==</span> <span class="st">"Georgia"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Running linear regression based on georgia</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>georgia_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Data_Value <span class="sc">~</span> Year, <span class="at">data =</span> georgia_data)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing regression summary for goergia</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(georgia_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Data_Value ~ Year, data = georgia_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-62223438 -24447136   1385557  14666922  80405143 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -6.130e+09  6.714e+08  -9.131 4.55e-12 ***
Year         3.133e+06  3.366e+05   9.308 2.51e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 34350000 on 48 degrees of freedom
Multiple R-squared:  0.6435,    Adjusted R-squared:  0.6361 
F-statistic: 86.64 on 1 and 48 DF,  p-value: 2.512e-12</code></pre>
</div>
</div>
<p>Furthermore, we will also express the relation for Alabama.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data for alabama</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>alabama_data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LocationDesc <span class="sc">==</span> <span class="st">"Alabama"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Runing linear regression for alabama dataset</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>alabama_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Data_Value <span class="sc">~</span> Year, <span class="at">data =</span> alabama_data)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing regression summary for alabama model</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(alabama_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Data_Value ~ Year, data = alabama_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-50502109 -13652199   5184908  11116529  42297840 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.878e+09  4.319e+08   -11.3 4.06e-15 ***
Year         2.491e+06  2.165e+05    11.5 2.12e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 22100000 on 48 degrees of freedom
Multiple R-squared:  0.7339,    Adjusted R-squared:  0.7283 
F-statistic: 132.4 on 1 and 48 DF,  p-value: 2.117e-15</code></pre>
</div>
</div>
<p>From the two regression models above, the relation can be clearly observed and the properties of the datasets are clearly expressed.</p>
</section>
<section id="summary-of-revenue-across-the-five-states-of-the-final-dataset" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="summary-of-revenue-across-the-five-states-of-the-final-dataset"><span class="header-section-number">5.3</span> Summary of Revenue across the five states of the final dataset</h2>
<p>We will will now provide the full statistical summary of revenue based on the States present in our dataset including the mean, meadian, maximum and the minimums.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarizing Data Value for five selected states</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>summary_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LocationDesc <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Georgia"</span>, <span class="st">"Kansas"</span>, <span class="st">"Idaho"</span>, <span class="st">"Alabama"</span>, <span class="st">"Nebraska"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LocationDesc) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>(), <span class="co"># provides no. of observation</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># provides mean</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co">#provides meadian</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># provides minimum value</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co">#provides max value</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># provides standard deviation</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the summary result</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  LocationDesc count      mean   median      min      max        sd
  &lt;chr&gt;        &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Alabama         31 64412390. 72144256 36739131 77175083 13404642.
2 Georgia         31 80889810. 85549591 40789310 92494239 11900995.
3 Idaho           31 13511795.  9777154  5142000 26264174  6580881.
4 Kansas          31 43645409. 45327675 21175000 62374658 12755999.
5 Nebraska        31 32675236. 31636000 12529000 48966120 10851763.</code></pre>
</div>
</div>
</section>
<section id="summary-of-variables" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="summary-of-variables"><span class="header-section-number">5.4</span> Summary of variables</h2>
<p>This table provides the overall summary of the final datset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> LocationDesc       LocationAbbr            Year        Data_Value      
 Length:155         Length:155         Min.   :1970   Min.   : 5142000  
 Class :character   Class :character   1st Qu.:1977   1st Qu.:24687170  
 Mode  :character   Mode  :character   Median :1985   Median :45327675  
                                       Mean   :1985   Mean   :47026928  
                                       3rd Qu.:1993   3rd Qu.:72472412  
                                       Max.   :2000   Max.   :92494239  
 GeoLocation       
 Length:155        
 Class :character  
 Mode  :character  
                   
                   
                   </code></pre>
</div>
</div>
<p>This section contributed by Mohammed Zuber</p>
</section>
<section id="load-required-libraries" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="load-required-libraries"><span class="header-section-number">5.5</span> Load Required Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries for data processing and visualization</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)  <span class="co"># For reading Excel files</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)   <span class="co"># For data manipulation</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># For visualization</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-original-data" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="load-the-original-data"><span class="header-section-number">5.6</span> Load the Original Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path to the dataset</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure the dataset is in the working directory</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"cigarette-tax.xlsx"</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the dataset from the specified sheet in the Excel file</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(data_path, <span class="at">sheet =</span> <span class="st">"cigarette-tax"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows to understand the dataset structure</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  LocationAbbr LocationDesc  Year Datasource TopicDesc    MeasureDesc Data_Value
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;
1 AL           Alabama       2019 OW         The Tax Bur… Cigarette …  165763113
2 AK           Alaska        2019 OW         The Tax Bur… Cigarette …   44773153
3 AZ           Arizona       2019 OW         The Tax Bur… Cigarette …  296712275
4 AR           Arkansas      2019 OW         The Tax Bur… Cigarette …  161909335
5 CA           California    2019 OW         The Tax Bur… Cigarette … 1791254942
6 CO           Colorado      2019 OW         The Tax Bur… Cigarette …  145551255
# ℹ 7 more variables: Data_Value_Unit &lt;chr&gt;, Data_Value_Type &lt;chr&gt;,
#   GeoLocation &lt;chr&gt;, Source &lt;chr&gt;, TopicTypeId &lt;chr&gt;, TopicId &lt;chr&gt;,
#   MeasureId &lt;chr&gt;</code></pre>
</div>
</div>
<p>We will now import the data from our repository using the here command. We can observe that there are 2550 observations with 14 variables. The variables some observations can be viewed using the head() command.</p>
</section>
<section id="generate-synthetic-data--llm-ai-tools-were-used-to-help-write-the-code" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="generate-synthetic-data--llm-ai-tools-were-used-to-help-write-the-code"><span class="header-section-number">5.7</span> Generate Synthetic Data- LLM AI tools were used to help write the code</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy the original dataset to preserve its structure</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>synthetic_df <span class="ot">&lt;-</span> df</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic values for the 'Data_Value' column</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The values are randomly sampled within the original range</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>synthetic_df<span class="sc">$</span>Data_Value <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min</span>(df<span class="sc">$</span>Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)<span class="sc">:</span><span class="fu">max</span>(df<span class="sc">$</span>Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="fu">nrow</span>(df), </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">replace =</span> <span class="cn">TRUE</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the synthetic dataset to verify changes</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(synthetic_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  LocationAbbr LocationDesc  Year Datasource TopicDesc    MeasureDesc Data_Value
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;            &lt;int&gt;
1 AL           Alabama       2019 OW         The Tax Bur… Cigarette … 1784329036
2 AK           Alaska        2019 OW         The Tax Bur… Cigarette … 1231722496
3 AZ           Arizona       2019 OW         The Tax Bur… Cigarette …  611534923
4 AR           Arkansas      2019 OW         The Tax Bur… Cigarette … 1018881505
5 CA           California    2019 OW         The Tax Bur… Cigarette …  677017575
6 CO           Colorado      2019 OW         The Tax Bur… Cigarette … 1869612235
# ℹ 7 more variables: Data_Value_Unit &lt;chr&gt;, Data_Value_Type &lt;chr&gt;,
#   GeoLocation &lt;chr&gt;, Source &lt;chr&gt;, TopicTypeId &lt;chr&gt;, TopicId &lt;chr&gt;,
#   MeasureId &lt;chr&gt;</code></pre>
</div>
</div>
<p>I created a synthetic dataset by copying the structure of the original dataset and replacing the Data_Value column with randomly sampled values within its original range. This ensures that the synthetic data maintains a similar distribution while removing any real-world patterns. While the minimum and maximum values are preserved, the randomness may not reflect trends or correlations present in the original data.</p>
</section>
</section>
<section id="data-cleaning-for-synthetic-data" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Data Cleaning for Synthetic Data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values and summary statistics</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> LocationAbbr       LocationDesc            Year       Datasource       
 Length:2550        Length:2550        Min.   :1970   Length:2550       
 Class :character   Class :character   1st Qu.:1982   Class :character  
 Mode  :character   Mode  :character   Median :1994   Mode  :character  
                                       Mean   :1994                     
                                       3rd Qu.:2007                     
                                       Max.   :2019                     
  TopicDesc         MeasureDesc          Data_Value        Data_Value_Unit   
 Length:2550        Length:2550        Min.   :2.811e+06   Length:2550       
 Class :character   Class :character   1st Qu.:4.743e+08   Class :character  
 Mode  :character   Mode  :character   Median :9.411e+08   Mode  :character  
                                       Mean   :9.422e+08                     
                                       3rd Qu.:1.411e+09                     
                                       Max.   :1.887e+09                     
 Data_Value_Type    GeoLocation           Source          TopicTypeId       
 Length:2550        Length:2550        Length:2550        Length:2550       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
   TopicId           MeasureId        
 Length:2550        Length:2550       
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the structure of the synthetic dataset</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(synthetic_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,550 × 14] (S3: tbl_df/tbl/data.frame)
 $ LocationAbbr   : chr [1:2550] "AL" "AK" "AZ" "AR" ...
 $ LocationDesc   : chr [1:2550] "Alabama" "Alaska" "Arizona" "Arkansas" ...
 $ Year           : num [1:2550] 2019 2019 2019 2019 2019 ...
 $ Datasource     : chr [1:2550] "OW" "OW" "OW" "OW" ...
 $ TopicDesc      : chr [1:2550] "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" "The Tax Burden on Tobacco" ...
 $ MeasureDesc    : chr [1:2550] "Cigarette Sales" "Cigarette Sales" "Cigarette Sales" "Cigarette Sales" ...
 $ Data_Value     : int [1:2550] 1784329036 1231722496 611534923 1018881505 677017575 1869612235 1738008298 356796171 1678682950 1023251209 ...
 $ Data_Value_Unit: chr [1:2550] "$" "$" "$" "$" ...
 $ Data_Value_Type: chr [1:2550] "Dollars" "Dollars" "Dollars" "Dollars" ...
 $ GeoLocation    : chr [1:2550] "POINT (-86.631860762 32.840571122)" "POINT (-147.722059036 64.845079957001)" "POINT (-111.763811277 34.86597028)" "POINT (-92.274490743 34.748650124)" ...
 $ Source         : chr [1:2550] "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" "Table 12- Orzechowski and Walker, Tax Burden on Tobacco" ...
 $ TopicTypeId    : chr [1:2550] "POL" "POL" "POL" "POL" ...
 $ TopicId        : chr [1:2550] "450POL" "450POL" "450POL" "450POL" ...
 $ MeasureId      : chr [1:2550] "450CGS" "450CGS" "450CGS" "450CGS" ...</code></pre>
</div>
</div>
<p>To assess the quality of the synthetic dataset, I checked for missing values and generated summary statistics using the summary() function. This provides key metrics such as the minimum, maximum, median, and quartiles, allowing for a comparison with the original dataset. Additionally, the str() function was used to confirm the structure and data types of each column, ensuring consistency with the original dataset. This step helps verify that the synthetic data retains the expected format and completeness before further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values (NA) within the synthetic dataset</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(synthetic_df))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the number of missing values for each column</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   LocationAbbr    LocationDesc            Year      Datasource       TopicDesc 
              0               0               0               0               0 
    MeasureDesc      Data_Value Data_Value_Unit Data_Value_Type     GeoLocation 
              0               0               0               0               0 
         Source     TopicTypeId         TopicId       MeasureId 
              0               0               0               0 </code></pre>
</div>
</div>
<p>To ensure data completeness, I checked for missing values in the synthetic dataset using colSums(is.na(synthetic_df)), which calculates the number of NA values in each column. ## Confirming the Structure of the Dataset Across States</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting the number of observations per State</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>state_counts <span class="ot">&lt;-</span> synthetic_df <span class="sc">%&gt;%</span> <span class="fu">count</span>(LocationDesc)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View the result</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 2
   LocationDesc             n
   &lt;chr&gt;                &lt;int&gt;
 1 Alabama                 50
 2 Alaska                  50
 3 Arizona                 50
 4 Arkansas                50
 5 California              50
 6 Colorado                50
 7 Connecticut             50
 8 Delaware                50
 9 District of Columbia    50
10 Florida                 50
# ℹ 41 more rows</code></pre>
</div>
</div>
<p>To assess the distribution of observations across states in the synthetic dataset, I utilized the count() function from the dplyr package. This function tallies the number of occurrences for each unique value in the specified column, in this case, LocationDesc. By executing synthetic_df %&gt;% count(LocationDesc), I obtained a summary of how many records pertain to each state. ## Filtering Five States for Further Analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter dataset for selected states</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>filtered_states <span class="ot">&lt;-</span> synthetic_df <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LocationDesc <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Georgia"</span>, <span class="st">"Kansas"</span>, <span class="st">"Idaho"</span>, <span class="st">"Alabama"</span>, <span class="st">"Nebraska"</span>))</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new dataset</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(filtered_states)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  LocationAbbr LocationDesc  Year Datasource TopicDesc    MeasureDesc Data_Value
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;            &lt;int&gt;
1 AL           Alabama       2019 OW         The Tax Bur… Cigarette … 1784329036
2 GA           Georgia       2019 OW         The Tax Bur… Cigarette … 1669690063
3 ID           Idaho         2019 OW         The Tax Bur… Cigarette …   34207889
4 KS           Kansas        2019 OW         The Tax Bur… Cigarette … 1857140875
5 NE           Nebraska      2019 OW         The Tax Bur… Cigarette …  832504060
6 AL           Alabama       2018 OW         The Tax Bur… Cigarette …  484349853
# ℹ 7 more variables: Data_Value_Unit &lt;chr&gt;, Data_Value_Type &lt;chr&gt;,
#   GeoLocation &lt;chr&gt;, Source &lt;chr&gt;, TopicTypeId &lt;chr&gt;, TopicId &lt;chr&gt;,
#   MeasureId &lt;chr&gt;</code></pre>
</div>
</div>
<p>To streamline the analysis, I filtered the dataset to include only five selected states: Georgia, Kansas, Idaho, Alabama, and Nebraska. This was done using the filter() function from dplyr, which extracts rows where the LocationDesc column matches one of the specified states. ## Selecting Relevant Variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only the required columns</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> filtered_states <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LocationDesc, LocationAbbr, Year, Data_Value, GeoLocation)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the new dataset</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  LocationDesc LocationAbbr  Year Data_Value GeoLocation                        
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;                              
1 Alabama      AL            2019 1784329036 POINT (-86.631860762 32.840571122) 
2 Georgia      GA            2019 1669690063 POINT (-83.627580346 32.839681093) 
3 Idaho        ID            2019   34207889 POINT (-114.363730042 43.682630005)
4 Kansas       KS            2019 1857140875 POINT (-98.200781227 38.3477403)   
5 Nebraska     NE            2019  832504060 POINT (-99.365720623 41.6410409880…
6 Alabama      AL            2018  484349853 POINT (-86.631860762 32.840571122) </code></pre>
</div>
</div>
<p>To focus on key information, I selected only the most relevant variables from the filtered dataset using the select() function from dplyr. The chosen columns—LocationDesc (state name), LocationAbbr (state abbreviation), Year, Data_Value (cigarette sales/revenue), and GeoLocation (state coordinates)—are essential for analyzing trends over time.</p>
<section id="scatter-plot-of-revenue-across-time-for-selected-states" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="scatter-plot-of-revenue-across-time-for-selected-states"><span class="header-section-number">6.1</span> Scatter Plot of Revenue Across Time for Selected States</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define custom colors for each state</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Georgia"</span> <span class="ot">=</span> <span class="st">"red"</span>, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Kansas"</span> <span class="ot">=</span> <span class="st">"blue"</span>, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Idaho"</span> <span class="ot">=</span> <span class="st">"green"</span>, </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Nebraska"</span> <span class="ot">=</span> <span class="st">"purple"</span>, </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Alabama"</span> <span class="ot">=</span> <span class="st">"orange"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot of Year vs Data_Value</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Data_Value, <span class="at">color =</span> LocationDesc)) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> custom_colors) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Data_Value Over Time for Selected States"</span>,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Data Value"</span>,</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"State"</span>) <span class="sc">+</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The key difference between my scatter plot and my classmate’s is that mine appears randomly distributed, while theirs shows a clear trend over time, with values increasing before 2000 and declining afterward. This is because I generated my synthetic data using random sampling, which removed any underlying structure present in the original dataset. My classmate’s data retains a progressive pattern, suggesting that Data_Value follows a time-dependent trend. ## Further Cleaning: Filtering Data for 1970-2000</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering dataset for years less than 2001</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&lt;</span> <span class="dv">2001</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the first few rows of the newly filtered dataset</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  LocationDesc LocationAbbr  Year Data_Value GeoLocation                        
  &lt;chr&gt;        &lt;chr&gt;        &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;                              
1 Alabama      AL            2000 1226607262 POINT (-86.631860762 32.840571122) 
2 Georgia      GA            2000  695213645 POINT (-83.627580346 32.839681093) 
3 Idaho        ID            2000 1592713712 POINT (-114.363730042 43.682630005)
4 Kansas       KS            2000  748675169 POINT (-98.200781227 38.3477403)   
5 Nebraska     NE            2000 1061013837 POINT (-99.365720623 41.6410409880…
6 Alabama      AL            1999 1074575607 POINT (-86.631860762 32.840571122) </code></pre>
</div>
</div>
<p>To focus on historical trends, I filtered the dataset to include only records from years before 2001 using the filter() function. This step ensures that the analysis captures a consistent time period, especially if later years exhibit different trends or irregularities. By restricting the data to 1970-2000, I aim to observe stable patterns without the potential disruptions seen in later years.</p>
</section>
<section id="confirming-observations-per-state" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="confirming-observations-per-state"><span class="header-section-number">6.2</span> Confirming Observations Per State</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting the number of observations per state again.</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>state_counts2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">count</span>(LocationDesc)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the count result</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_counts2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  LocationDesc     n
  &lt;chr&gt;        &lt;int&gt;
1 Alabama         31
2 Georgia         31
3 Idaho           31
4 Kansas          31
5 Nebraska        31</code></pre>
</div>
</div>
<p>To verify the distribution of observations across states after filtering, I used the count() function again to tally the number of records per state in the refined dataset. This step ensures that all selected states (Georgia, Kansas, Idaho, Alabama, and Nebraska) maintain a balanced representation after restricting the data to years before 2001.</p>
</section>
<section id="association-of-variables-scatter-plot-with-trend-line" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="association-of-variables-scatter-plot-with-trend-line"><span class="header-section-number">6.3</span> Association of Variables: Scatter Plot with Trend Line</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Data_Value, <span class="at">color =</span> LocationDesc)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Adding a linear trend line</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trend of Revenue from Cigarette(in US$) Over Years by State"</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Revenue Value"</span>,</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"State"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The key difference between my plot and my classmate’s is that my trend lines appear flatter, while theirs show a clear upward trajectory over time. This is because my synthetic Data_Value was generated randomly, removing any inherent growth patterns present in the original dataset. My classmate’s plot maintains a structured increase, indicating that revenue values naturally rise over time rather than fluctuating randomly.</p>
</section>
<section id="regression-analysis-relationship-over-time" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="regression-analysis-relationship-over-time"><span class="header-section-number">6.4</span> Regression Analysis: Relationship Over Time</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data for Georgia</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>georgia_data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LocationDesc <span class="sc">==</span> <span class="st">"Georgia"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Running linear regression based on Georgia</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>georgia_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Data_Value <span class="sc">~</span> Year, <span class="at">data =</span> georgia_data)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing regression summary for Georgia</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(georgia_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Data_Value ~ Year, data = georgia_data)

Residuals:
       Min         1Q     Median         3Q        Max 
-974428520 -333610875  -49039365  449037525  889230815 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  3.899e+09  1.026e+10   0.380    0.705
Year        -1.446e+06  5.142e+06  -0.281    0.780

Residual standard error: 524700000 on 48 degrees of freedom
Multiple R-squared:  0.001644,  Adjusted R-squared:  -0.01915 
F-statistic: 0.07906 on 1 and 48 DF,  p-value: 0.7798</code></pre>
</div>
</div>
<p>The dataset maintains the original structure, with each selected state having 50 observations, ensuring consistency. However, the regression analysis for Georgia shows a very low R-squared value (0.00164) and a high p-value (0.7798), indicating no clear trend over time. This suggests that the synthetic Data_Value was randomly assigned and does not reflect a structured increase or decrease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data for Alabama</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>alabama_data <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LocationDesc <span class="sc">==</span> <span class="st">"Alabama"</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Running linear regression for Alabama dataset</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>alabama_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Data_Value <span class="sc">~</span> Year, <span class="at">data =</span> alabama_data)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing regression summary for Alabama model</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(alabama_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Data_Value ~ Year, data = alabama_data)

Residuals:
       Min         1Q     Median         3Q        Max 
-842238895 -386165861   38772300  400649003  842216045 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -4.996e+09  9.614e+09  -0.520    0.606
Year         2.961e+06  4.820e+06   0.614    0.542

Residual standard error: 491900000 on 48 degrees of freedom
Multiple R-squared:  0.0078,    Adjusted R-squared:  -0.01287 
F-statistic: 0.3773 on 1 and 48 DF,  p-value: 0.5419</code></pre>
</div>
</div>
<p>The regression analysis for Alabama shows a low R-squared value (0.0078) and a high p-value (0.5419), indicating that Year does not significantly explain the variation in Data_Value. The near-zero R-squared suggests that the synthetic revenue values do not follow a clear increasing or decreasing trend over time. This likely results from the random assignment of Data_Value, which does not capture the expected real-world growth or decline. ## Summary Statistics of Revenue for Selected States</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarizing Data Value for five selected states</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>summary_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LocationDesc) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>(), </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(Data_Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the summary result</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  LocationDesc count        mean     median       min        max         sd
  &lt;chr&gt;        &lt;int&gt;       &lt;dbl&gt;      &lt;int&gt;     &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
1 Alabama         31  897512416.  960156234  48443527 1592272124 459682451.
2 Georgia         31 1041163227.  931027872 119283033 1795190468 483486517.
3 Idaho           31  962935962.  953346293  37056961 1801657976 502962014.
4 Kansas          31  940194286.  927004867 133488936 1853330662 507391652.
5 Nebraska        31 1045789591. 1068338750  14826708 1851782104 515086985.</code></pre>
</div>
</div>
<p>The summary statistics for the five selected states indicate that each state has 31 observations, maintaining a balanced dataset. However, the mean and median values show high variability, suggesting inconsistencies in how Data_Value was generated. The wide range between min and max values and high standard deviation indicate that the synthetic data may still be too random rather than following a structured trend. ## Final Summary of the Dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> LocationDesc       LocationAbbr            Year        Data_Value       
 Length:155         Length:155         Min.   :1970   Min.   :1.483e+07  
 Class :character   Class :character   1st Qu.:1977   1st Qu.:5.343e+08  
 Mode  :character   Mode  :character   Median :1985   Median :9.591e+08  
                                       Mean   :1985   Mean   :9.775e+08  
                                       3rd Qu.:1993   3rd Qu.:1.388e+09  
                                       Max.   :2000   Max.   :1.853e+09  
 GeoLocation       
 Length:155        
 Class :character  
 Mode  :character  
                   
                   
                   </code></pre>
</div>
</div>
<p>From the outputs, my synthetic dataset maintains the correct structure with selected variables such as LocationDesc, Year, and Data_Value, ensuring consistency. However, the regression analysis for Georgia and Alabama shows very low R-squared values (0.0016 and 0.0078, respectively) and high p-values (0.7798 and 0.5419), indicating no significant relationship between Year and Data_Value. Additionally, while the mean and median values for each state appear reasonable, the wide range and high standard deviation suggest excessive randomness in Data_Value generation.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>